apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-{{ .Release.Name }}
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-{{ .Release.Name }}
spec:
  hosts:
    - "*"
  gateways:
    - gateway-{{ .Release.Name }}
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: service-{{ .Release.Name }}-left
            port:
              number: {{ .Values.settings.left.port }}
          weight: 50
        - destination:
            host: service-{{ .Release.Name }}-right
            port:
              number: {{ .Values.settings.right.port }}
          weight: 50
